"""fix_wallet

Revision ID: cfddd8fc9803
Revises: b2a722ed7ab5
Create Date: 2024-02-09 14:51:23.875557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfddd8fc9803'
down_revision: Union[str, None] = 'b2a722ed7ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commission', 'update_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wallets', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('commission', 'update_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
