"""Add column

Revision ID: f6195fd5a18f
Revises: 88f87c89e162
Create Date: 2024-02-09 13:09:58.407256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6195fd5a18f'
down_revision: Union[str, None] = '88f87c89e162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE users ALTER COLUMN chat_id TYPE INTEGER USING chat_id::integer')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE users ALTER COLUMN chat_id TYPE VARCHAR USING chat_id::VARCHAR')
    # ### end Alembic commands ###